/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v2/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Capabilities */
        get: operations["capabilities_api_v2_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/exports/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Config */
        post: operations["config_api_v2_exports_config_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/exports/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pdf */
        post: operations["pdf_api_v2_exports_pdf_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/fit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fit */
        post: operations["fit_api_v2_fit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v2_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview */
        post: operations["preview_api_v2_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Annotations */
        Annotations: {
            /**
             * Show Frame Legend
             * @description Draw board-coordinate axes at the compensated target's top-left: +X right, +Y down, and +Z into the page.
             * @default false
             */
            show_frame_legend: boolean;
            /**
             * Show Parameters
             * @default true
             */
            show_parameters: boolean;
            /**
             * Show Ruler
             * @default true
             */
            show_ruler: boolean;
        };
        /** ArucoBoard */
        ArucoBoard: {
            /**
             * Columns
             * @default 5
             */
            columns: number;
            /**
             * Dictionary
             * @default DICT_5X5_100
             */
            dictionary: string;
            /**
             * Id Font Size Pt
             * @default 8
             */
            id_font_size_pt: number;
            /**
             * Marker Size Mm
             * @default 30
             */
            marker_size_mm: number;
            /**
             * Rows
             * @default 7
             */
            rows: number;
            /**
             * Separation Mm
             * @default 10
             */
            separation_mm: number;
            /**
             * Show Ids
             * @default false
             */
            show_ids: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "aruco";
        };
        /** CharucoBoard */
        CharucoBoard: {
            /**
             * Dictionary
             * @default DICT_5X5_250
             */
            dictionary: string;
            /**
             * Marker Size Mm
             * @default 18
             */
            marker_size_mm: number;
            /**
             * Square Size Mm
             * @default 30
             */
            square_size_mm: number;
            /**
             * Squares X
             * @default 5
             */
            squares_x: number;
            /**
             * Squares Y
             * @default 7
             */
            squares_y: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "charuco";
        };
        /** Checkerboard */
        Checkerboard: {
            /**
             * Border Mm
             * @default 20
             */
            border_mm: number;
            /**
             * Square Size Mm
             * @default 30
             */
            square_size_mm: number;
            /**
             * Squares X
             * @default 5
             */
            squares_x: number;
            /**
             * Squares Y
             * @default 8
             */
            squares_y: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "checkerboard";
        };
        /** CoordinateFrame */
        CoordinateFrame: {
            /**
             * Enabled
             * @default false
             */
            enabled: boolean;
            /**
             * @default {
             *       "pitch_deg": 0,
             *       "roll_deg": 0,
             *       "translation_x_m": 0,
             *       "translation_y_m": 0,
             *       "translation_z_m": 0,
             *       "yaw_deg": 0
             *     }
             */
            pose: components["schemas"]["Pose"];
        };
        /** FitChange */
        FitChange: {
            /** After */
            after: number;
            /** Before */
            before: number;
            /** Field */
            field: string;
        };
        /** FitResponse */
        FitResponse: {
            /** Adjusted */
            adjusted: boolean;
            /**
             * Changes
             * @default []
             */
            changes: components["schemas"]["FitChange"][];
            request: components["schemas"]["GenerateRequest"];
            /** Scale Factor */
            scale_factor: number;
        };
        /** GenerateRequest */
        GenerateRequest: {
            /**
             * @default {
             *       "show_frame_legend": false,
             *       "show_parameters": true,
             *       "show_ruler": true
             *     }
             */
            annotations: components["schemas"]["Annotations"];
            /**
             * Board
             * @default {
             *       "columns": 5,
             *       "dictionary": "DICT_5X5_100",
             *       "id_font_size_pt": 8,
             *       "marker_size_mm": 30,
             *       "rows": 7,
             *       "separation_mm": 10,
             *       "show_ids": false,
             *       "type": "aruco"
             *     }
             */
            board: components["schemas"]["ArucoBoard"] | components["schemas"]["CharucoBoard"] | components["schemas"]["Checkerboard"];
            /**
             * @default {
             *       "enabled": false,
             *       "pose": {
             *         "pitch_deg": 0,
             *         "roll_deg": 0,
             *         "translation_x_m": 0,
             *         "translation_y_m": 0,
             *         "translation_z_m": 0,
             *         "yaw_deg": 0
             *       }
             *     }
             */
            coordinate_frame: components["schemas"]["CoordinateFrame"];
            /**
             * @default {
             *       "orientation": "portrait",
             *       "paper_size": "A4"
             *     }
             */
            page: components["schemas"]["Page"];
            /**
             * @default {
             *       "x_percent": 100,
             *       "y_percent": 100
             *     }
             */
            print_compensation: components["schemas"]["PrintCompensation"];
            /**
             * Schema Version
             * @default 2.0
             * @constant
             */
            schema_version: "2.0";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Page */
        Page: {
            /**
             * Orientation
             * @default portrait
             * @enum {string}
             */
            orientation: "portrait" | "landscape";
            /**
             * Paper Size
             * @default A4
             * @enum {string}
             */
            paper_size: "A4" | "A3" | "A2" | "A1" | "A5" | "A6" | "Letter" | "Legal";
        };
        /** Pose */
        Pose: {
            /**
             * Pitch Deg
             * @default 0
             */
            pitch_deg: number;
            /**
             * Roll Deg
             * @default 0
             */
            roll_deg: number;
            /**
             * Translation X M
             * @default 0
             */
            translation_x_m: number;
            /**
             * Translation Y M
             * @default 0
             */
            translation_y_m: number;
            /**
             * Translation Z M
             * @default 0
             */
            translation_z_m: number;
            /**
             * Yaw Deg
             * @default 0
             */
            yaw_deg: number;
        };
        /** PrintCompensation */
        PrintCompensation: {
            /**
             * X Percent
             * @default 100
             */
            x_percent: number;
            /**
             * Y Percent
             * @default 100
             */
            y_percent: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    capabilities_api_v2_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    config_api_v2_exports_config_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pdf_api_v2_exports_pdf_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fit_api_v2_fit_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FitResponse"];
                };
            };
            /** @description No safe reduced configuration exists */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    health_api_v2_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    preview_api_v2_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
