[server]
headless = true
enableCORS = false
enableXsrfProtection = true
serverRunOnSave = false

[browser]
gatherUsageStats = false
toolbarMode = "viewer"

[theme]
primaryColor = "rgb(177, 203, 33)"
backgroundColor = "#424242"
secondaryBackgroundColor = "#2e2e2e"
textColor = "#fcfcfc"
font = "sans serif"